### ISSUE TITLE
blog list padding too much

### ISSUE THREAD

**Issue by BirnadinErick** [BirnadinErick/spc-175#31]
reduce the padding(x) of blog list in the site. Apparently, the padding is still the previous not the new `px-6`.

**Comment by Tharshan-dilky** [comment]
I have clear it can you please check it

**Comment by BirnadinErick** [comment]
where @Tharshan-dilky? this pull request doesn't have any commits?

Plz check whether you made the pull request.

**Comment by BirnadinErick** [comment]
> where @Tharshan-dilky? this pull request doesn't have any commits?
> 
> Plz check whether you made the pull request.

All good now.

**Comment by BirnadinErick** [comment]
Featured images on `/academics` and `/sports` also need to be updated
